name: edufun_1
description: "Aplikasi Edukasi untuk Anak SD Kelas 1 - Kurikulum Merdeka 2025"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  audioplayers: ^6.5.1
  lottie: ^3.1.2
  provider: ^6.1.1
  sqflite: ^2.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  animations: ^2.0.11
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
