name: edufun_1
description: "Aplikasi Edukasi untuk Anak SD Kelas 1 - Kurikulum Merdeka 2025"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  lottie: ^2.7.0
  provider: ^6.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
